### ISSUE TITLE
Complete the Documentation of findings of Uref economics research

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#215] opened 2023-08-31 20:29 UTC
Cost is set based on the URef lifetime requested (more eras, more cost); economics will be set to motivate cost effective usage: longer lifetimes are more expensive because they are held in global state longer.
Must handle refreshing lifetimes (more cost?)

In the previous sprint, research was conducted.    Now the findings must be written.

**Comment by AlexanderLimonov** [comment] 2023-09-19 22:57
Duplicate of #211

**Closed as completed by AlexanderLimonov** 2023-09-19 22:57 UTC
